#!/usr/bin/env python3
"""Regenerate bosun/_logo.py (the inlined header logo + tab favicon) from the
source image. Requires Pillow (dev-only; not a runtime dependency).

    python3 scripts/gen_logo.py

To change the logo: replace assets/bosun-logo.png and re-run this.
"""
import base64
import io

from PIL import Image, ImageDraw

SRC = "assets/bosun-logo.png"
OUT = "bosun/_logo.py"


def _uri(src, size, radius_frac):
    im = src.resize((size, size), Image.LANCZOS).convert("RGBA")
    mask = Image.new("L", (size, size), 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, size - 1, size - 1],
                                           radius=int(size * radius_frac), fill=255)
    im.putalpha(mask)
    buf = io.BytesIO()
    im.save(buf, "PNG", optimize=True)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


def main():
    src = Image.open(SRC).convert("RGB")
    with open(OUT, "w") as f:
        f.write("# Generated by scripts/gen_logo.py from assets/bosun-logo.png -- do not edit by hand.\n")
        f.write("LOGO = %r\n" % _uri(src, 128, 0.22))     # header, displayed ~56px
        f.write("FAVICON = %r\n" % _uri(src, 32, 0.15))   # browser tab
    print("wrote", OUT)


if __name__ == "__main__":
    main()
